name: Release
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
    - run: npx semantic-release
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
